### ISSUE TITLE
OpenVPN configuration files

### ISSUE THREAD

**Issue by Solrunn** [hwdsl2/openvpn-install#10]
The openvpn client configuration is straigthforward for mobile openvpn but not desktop if not using a graphical network manager as a configuration file has to be manually written.
It would be really nice to have an openvpn .ovpn config file generated (only the mobile .mobileconfig is).

**Comment by hwdsl2** [comment]
@Solrunn Hello! I moved this issue to the correct repository. For OpenVPN, the script does create a `.ovpn` file which you can transfer to your desktop clients (e.g. Windows). If you were referring to IKEv2 instead of OpenVPN, Windows does not currently support client configuration files for IKEv2. Therefore you'll need to transfer and import the `.p12` file using the [instructions](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#configure-ikev2-vpn-clients).
